### ISSUE TITLE
Azure Pipeline: error XA0030: Building with JDK version `14.0.2` is not supported. Please install JDK version `11.0`

### ISSUE THREAD

**Issue by Axemasta** [xamarin/xamarin-android#5999]
I tried to run my release pipeline today and noticed it failing with the following error:

```
"/Users/runner/work/1/s/src/****.Mobile.sln" (default target) (1) ->
"/Users/runner/work/1/s/src/App/****.Controls/****.Controls.csproj" (default target) (6:36) ->
"/Users/runner/work/1/s/src/App/****.Controls/****.Controls.csproj" (Build target) (6:39) ->
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Legacy.targets(248,5): error XA0030: Building with JDK version `14.0.2` is not supported. Please install JDK version `11.0`. See https://aka.ms/xamarin/jdk9-errors [/Users/runner/work/1/s/src/App/****.Controls/****.Controls.csproj]
```

I've seen #5864 recently reported the issue and #4853 doesn't seem to apply to this situation. My project builds fine on 3 local machines (2 macs & 1 windows) so i'm confident in the product. I can't seem to override the jdk version on the azure agent, I pulled the code and looked for references to JDK11 and added the following YAML to my pipeline before calling build:

``` YAML
- script: echo "##vso[task.setvariable variable=PATH]$PATH:$HOME/android-toolchain/$(XA.Jdk11.Folder)/bin"
  displayName: append jdk tools to PATH

- script: |
    echo ##vso[task.setvariable variable=JI_JAVA_HOME]%USERPROFILE%\android-toolchain\$(XA.Jdk11.Folder)
  displayName: set JI_JAVA_HOME
```

But i'm not sure where exactly I need to put that or if i need to override something else. I also had a look at the [`JavaToolInstaller@0`](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops) task but couldnt get that working either.

My last run of this pipeline was 04-May-2021 and very little has changed since then and now, the commit that previously built & is now released also failed to pass the pipeline on todays date.

### Steps to Reproduce

I have excluded this info from this issue since it relates to my personal codebase.

### Version Information

I am using a macOS azure agent with the config:
``` YAML
VMImage: 'macOS-latest'
```

### Log File

Attached is the build log for the Xamarin@iOS task, It might seem weird this is breaking my iOS app but the iOS & Android projects shared a .NET Standard library that targets multiple platforms & contains things like custom renderers etc (like how XCT or XE works).

[XA0030 Pipeline Log.txt](https://github.com/xamarin/xamarin-android/files/6600244/XA0030.Pipeline.Log.txt)

I have replace the name of my project with ACME fyi 😛

**Comment by jonathanpeppers** [comment]
So I've noticed since VS 16.10 went GA, I've had to add workarounds such as:

* https://github.com/jonathanpeppers/boots/commit/4633dc8d0a26eba90436c901149b7741669ac07c
* https://github.com/jonathanpeppers/boots/commit/d1bef4ff170101b837150db4ea7cb90812d21d8c

I've had to do this on Azure DevOps as well as Github Actions. (probably because they use similar machine images)

@jonpryor is there something we should do here? The problem is the image has `$JAVA_HOME` set to a JDK 14.

It doesn't seem like Xamarin.Android projects will build on these two CI products unless you set `$JI_JAVA_HOME` or `$JAVA_HOME` yourself.

**Comment by Axemasta** [comment]
Thanks @jonathanpeppers, I've got my pipeline running again 🥳

For those interested I added the following to my `.yml`, where I set runtime & use boots:
``` YAML
- script: echo '##vso[task.setvariable variable=JI_JAVA_HOME]$(JAVA_HOME_11_X64)'
  displayName: set JI_JAVA_HOME

- script: |
    export JI_JAVA_HOME="$JAVA_HOME_11_X64"
  displayName: Set Java Home Path
```

And I added the following variable to my pipeline:
| Name             | Value                                                                      |
|------------------|----------------------------------------------------------------------------|
| JAVA_HOME_11_X64 | `/Users/runner/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64/Contents/Home` |

Interestingly using the `JavaToolInstaller@0` task claims to set these variables:
``` YAML
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
```

Task output:
```
Use preinstalled JDK from /Users/runner/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64/Contents/Home
JAVA_HOME is being set to: /Users/runner/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64/Contents/Home
JAVA_HOME_11_X64 is being set to: /Users/runner/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64/Contents/Home
Prepending PATH environment variable with directory: /Users/runner/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64/Contents/Home/bin
Finishing: JavaToolInstaller
```

But the task still failed, it only succeeded when running the steps that @jonathanpeppers had linked. I set the pipeline variable from the path the tool outputs so that is odd, I imagine hardcoding this path will make my pipeline flakier but thats a bridge I will cross in the future. Hopefully anyone else experiencing this issue at the moment can fix their pipeline for the timebeing 🙂
