### ISSUE TITLE
Azure Pipeline Could not find a pool with name windows-2022 when building android 12

### ISSUE THREAD

**Issue by developer9969** [xamarin/xamarin-android#6504]
### Steps to Reproduce
I am using VS2022 to build our latest XF App  and microsoft hosted agents and I am trying to build against android 12 which is not supported by windows2019 image .

1. Change the VMImage to 'windows-2022'
2. Run the pipeline and I get
3. "Could not find a pool with name windows-2022"

I dont have a repo as such but all I am trying to do is build the android app in azure devops using windows-2022 so that I can set the android target to 12.

Any suggestions which hosted agent I shoud use?
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

many thanks

**Comment by jpobst** [comment]
We use `windows-2022`:

```
variables:
  HostedWinImage: windows-2022

jobs:
- job: windows_build
  displayName: Windows - .NET Framework
  pool:
    vmImage: $(HostedWinImage)
  timeoutInMinutes: 20
...
```

[(source)](https://github.com/xamarin/java.interop/blob/main/build-tools/automation/azure-pipelines.yaml)

If you're getting "Could not find a pool with name windows-2022" it sounds like maybe you are trying to set the pool to `windows-2022` instead of the vmImage to `windows-2022`.  The pool is called `Azure Pipelines`.

I think it used to work by calling the pool `windows-2019`, but then they changed to the new way.  The old way had a backwards-compatibility hack that allowed it to continue working.  I had to change the way we call it when we updated to `windows-2022`.
