### ISSUE TITLE
Not able to generate android app bundle

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#7539]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Not-able-to-generate-android-app-bundle/10186902)._

---
Hi, I am getting error while generating .aab file using azure devops

**Error:**
```
**MSBUILD : error MSB1009: Project file does not exist.
Switch: /Users/runner/work/1/s/CustomerOneAppAndroid/*.csproj**
```
Below **task** i am using for generating .aab file
```
 - task: Bash@3
   displayName: "Build and sign App Bundle"
   inputs:
     targetType: "inline"
     script: |
       msbuild -restore $(Build.SourcesDirectory)/CustomerOneAppAndroid/*.csproj -t:SignAndroidPackage -p:AndroidPackageFormat=aab -p:Configuration=$(buildConfiguration) -p:AndroidKeyStore=True -p:AndroidSigningKeyStore=$(keyStore.secureFilePath) -p:AndroidSigningStorePass=$(keystore_password) -p:AndroidSigningKeyAlias=$(keystore_alias) -p:AndroidSigningKeyPass=$(keystore_alias_password)
```

Could you please check this issue?

Looking forward for your reply!

Thanks,
Pooja

---
#### Feedback Bot on 11/1/2022, 06:58 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)
