### ISSUE TITLE
MSBuild '$(buildConfiguration)' regression when run on Azure Pipelines

### ISSUE THREAD

**Issue by projectgoav** [xamarin/xamarin-android#7609]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

Pipelines - `macos-12`

### Description

Have been directed here via:
- https://developercommunity.visualstudio.com/t/MSB6006:-java-exited-with-code-1/10180082
- https://github.com/actions/runner-images/issues/6687

I don't believe this is a Xamarin.Android bug but I am following the advice of the other people I have spoken to. 

### Steps to Reproduce

1. Create new Xamarin.Android Project
2. Create Azure Pipeline with the following task:
```
- task: XamarinAndroid@1
  inputs:
    projectFile: './<path_to>.csproj'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
    configuration: 'Debug'
    createAppPackage: false
```
3. Project will fail to build in Pipelines (`macos-latest` or `macos-12` machines. This doesn't happen in `macos-11`. 

If the pipeline task is replaced with:
```
- task: XamarinAndroid@1
  inputs:
    projectFile: './<path_to>.csproj'
    outputDirectory: '$(build.binariesDirectory)/<something_else>'
    configuration: 'Debug'
    createAppPackage: false
```

this build passess successfully. 

### Relevant log output

```shell
Logs and projects can be found in the 2 previously linked issues.
```
